
platform :ios, '9.0'
use_frameworks!

target 'SwiftTest' do
    
    pod 'Kingfisher', '~> 3.2.0'
    pod 'Alamofire', '~> 4.0.1'
    pod 'RxCocoa', '~> 3.0.1'
    pod 'RxSwift', '~> 3.0.1'
    pod 'Realm', '~> 2.0.3'
    pod 'FMDB', '~> 2.6.2'

end
